export interface Itable{
	data:{
            deal_id: number,
            deal_name: string,
            deal_type: string,
            deal_project_code: null,
            deal_type_id: string,
            raising_capital_amount: null,
            raising_capital_amount_secondary: null,
            raising_capital_currency_id: null,
            listing_exchange_id: null,
            updated_at: any,
            wall_crossed_deal: any,
            lead_sponsor_advisor: any,
            expected_capital_currency_id: any,
            expected_capital_amount: any,
            cornerstone_investors_name: any,
            other_lead_sponsor_advisor: any,
            other_information: any,
            description: string,
            valuation_timezone_id: any,
            pricing_timezone_id: any,
            valuation_date_from: any,
            valuation_date_to: any,
            pricing_date_to: any,
            pricing_date_from: any,
            wallcross_updated: boolean,
            DT_RowId: number,
            company_name: string,
            sectors: any,
            total:  number,
            exchange_name: string
    }
}